fix caching issue
miguelpruivo/flutter_file_picker pull request #1123
Opened 2022-09-15 13:41 UTC by abhi16180

2022-09-15 13:44 UTC, abhi16180 commented
> _ No description provided. _

@miguelpruivo  Please check it out

2022-09-16 10:49 UTC, miguelpruivo requested changes
Bump version to 5.2.0 and update CHANGELOG please.

2022-09-16 11:30 UTC, abhi16180 commented
> Bump version to 5.2.0 and update CHANGELOG please.

Done

2022-09-19 09:16 UTC, miguelpruivo approved these changes
LGTM.

2022-09-19 09:17 UTC, merged