fix(android): build.gradle namespace
miguelpruivo/flutter_file_picker pull request #1342
Opened 2023-08-07 07:06 UTC by DrBu7cher

Make it conditional, because it could break the build on Gradle < 8.0

2023-10-31 12:35 UTC, miguelpruivo reviewed
I have been using gradle < 8 without any issues without this. Would you mind to elaborate?

2023-11-02 20:00 UTC, navaronbracke commented
This is only an issue for the Android Gradle Plugin < 4.2 iirc

2023-11-02 20:02 UTC, navaronbracke requested changes

2023-11-02 20:02 UTC, navaronbracke commented on android/build.gradle
> +    if (project.android.hasProperty("namespace")) { namespace 'com.mr.flutter.plugin.filepicker' }
```suggestion
    if (project.android.hasProperty("namespace")) {
        namespace 'com.mr.flutter.plugin.filepicker' 
    }
```

2023-11-03 08:32 UTC, navaronbracke approved these changes

2023-11-04 15:40 UTC, merged