Fix issue 1367
miguelpruivo/flutter_file_picker pull request #1369
Opened 2023-09-12 20:04 UTC by GabrielAraujo

[Issue 1367](https://github.com/miguelpruivo/flutter_file_picker/issues/1367)

On iOS 17 the UTI type public.item is not properly working for live photos that are syncing with iCloud (download or upload).
Using media specific UTI types seemed to have fixed the problem but still any thoughts on the approach are welcome so we can adjust on how we handle the issue.

2023-09-12 20:05 UTC, GabrielAraujo commented
@miguelpruivo Please look at the Issue for more details.

2023-11-04 15:41 UTC, miguelpruivo commented
Is this still an issue with the latest iOS?

2023-11-21 12:08 UTC, devibrahimkarahan commented
I have iOS 17.1.1 and im getting an error when i choose live photo. With this PR, there is no error 👍🏻

2024-01-01 17:52 UTC, cdiethelm commented
Is this fix going to be approved? I have the exact same issue.

2024-03-04 17:40 UTC, miguelpruivo commented
Please rebase and update the version/changelog accordingly.

2024-03-25 13:50 UTC, GastonTestay commented
Do we have any news about this? 

@GabrielAraujo @miguelpruivo is there a chance that this PR could be merged into the main repository sooner rather than later? 🤔

2024-03-27 16:26 UTC, lboedy commented
Would be awesome to see this PR merge!

2024-03-28 11:41 UTC, zhouzhiyong619 commented
Please merge this PR as soon as possible?

2024-04-05 13:11 UTC, GastonTestay commented
We rebase & update the changelog the PR with main here:
https://github.com/miguelpruivo/flutter_file_picker/pull/1475

2024-05-16 06:53 UTC, Maatteogekko commented
Any update on this? I am getting the error more and more.
Is there something I can do to help get this merged sooner rather than later?

2024-08-25 10:40 UTC, miguelpruivo requested changes
Please rebase to main and I'll merge it right away. Sorry for the delay.

2024-08-30 14:23 UTC, GabrielAraujo commented
@miguelpruivo Rebased! Please merge this asap

2024-10-24 20:40 UTC, matiasmelendi commented
@miguelpruivo any chance you can merge this PR? It's been open for more than a year 🙏

2024-12-12 13:49 UTC, matiasmelendi commented
@GabrielAraujo any chance you can rebase the branch and update the version number?

2024-12-12 14:00 UTC, GabrielAraujo commented
@matiasmelendi do you have permissions to merge this? It has been a full year since we started this discussion but the maintainers never merge it and we need to keep constantly rebasing it ......

2024-12-12 21:49 UTC, matiasmelendi commented
I don't but I promise I will do my best to chase @miguelpruivo to re-review the PR and merge it. I really need this to be merged and released 🙏

2025-01-29 16:55 UTC, orestesgaolin commented
Reworked in #1693

2025-01-29 21:50 UTC, closed without merging

2025-01-30 19:01 UTC, matiasmelendi commented
Thank you @orestesgaolin 👏 you da king!