Fix for Android Example Project Gradle Issues
miguelpruivo/flutter_file_picker pull request #1661
Opened 2024-12-30 11:55 UTC by vicajilau

# Summary  
The Android directory in the example project was found to have outdated Gradle configurations, preventing compatibility with newer versions of Java and causing build issues. To resolve this, the Android folder was removed and regenerated using Flutter's CLI tool.

## Steps Taken  
1. **Remove the existing Android folder** from the example project.  
2. Regenerate it with the following command:  
   ```bash
   flutter create --platforms=android .

## Steps Taken
- Java Compatibility: The regenerated Android project now compiles successfully with newer versions of Java, ensuring compatibility with Java 21 and beyond.
- Gradle Version Alignment: The updated project uses a modern Gradle version that aligns with Flutter's latest tooling, as described in [The Flutter and Java 21 Mystery](https://www.victorcarreras.dev/2024/10/the-flutter-and-java-21-mystery-in.html).
- Improved Build Process: This fix not only resolves compatibility issues but also modernizes the Gradle setup for better stability and alignment with best practices.

## Conclusion
The changes provide a more robust and forward-compatible configuration for the example project's Android build.

<img width="127" alt="image" src="https://github.com/user-attachments/assets/ea0e0535-2108-4ffa-843c-5c5b4938ec34" />

2025-02-14 10:47 UTC, navaronbracke requested changes

2025-02-14 10:47 UTC, navaronbracke commented on example/.metadata
> -      create_revision: 4b12645012342076800eb701bcdfe18f87da21cf
The revision hashes for the other platforms are gone? Can you restore those? I don't know what impact this has on the rest of the code, though.

2025-02-14 10:47 UTC, navaronbracke commented on example/android/build.gradle
> -    gradle.projectsEvaluated {
Can you restore this block?

2025-02-14 10:47 UTC, navaronbracke commented on example/test/widget_test.dart
> +  testWidgets('Counter increments smoke test', (WidgetTester tester) async {
This test is irrelevant to the example and can be removed?

2025-02-14 10:47 UTC, navaronbracke commented on CHANGELOG.md
> +- Recreate android folder in example project. [@vicajilau](https://github.com/vicajilau)
Minor docs suggestion

```suggestion
- Updated example project Android sources. [@vicajilau](https://github.com/vicajilau)
```

2025-02-14 10:47 UTC, navaronbracke commented on example/android/app/src/main/kotlin/com/mr/flutter/plugin/filepicker/file_picker_example/MainActivity.kt
> +package com.mr.flutter.plugin.filepicker.file_picker_example
What is the difference with this one and the old (Kotlin) one? Was the old directory structure not correct?

2025-02-14 10:47 UTC, navaronbracke commented on example/android/app/src/main/AndroidManifest.xml
> -    <uses-permission android:name="android.permission.INTERNET"/>
What happened to these two permissions? Can you give some clarification as to why both are gone?

2025-02-14 11:41 UTC, vicajilau commented on example/test/widget_test.dart
> +  testWidgets('Counter increments smoke test', (WidgetTester tester) async {
Done!!

2025-02-14 11:41 UTC, vicajilau commented on example/android/build.gradle
> -    gradle.projectsEvaluated {
Done!!

2025-02-14 11:51 UTC, vicajilau commented on example/android/app/src/main/AndroidManifest.xml
> -    <uses-permission android:name="android.permission.INTERNET"/>
These are no longer required in the latest versions of Flutter. They came by default in older versions, but if you create an empty project you will see that they no longer appear in the manifest.

2025-02-14 11:57 UTC, vicajilau commented on example/android/app/src/main/AndroidManifest.xml
> -    <uses-permission android:name="android.permission.INTERNET"/>
The `WRITE_EXTERNAL_STORAGE` permission should be back and I just returned it. However, the `INTERNET` permission is not needed in the latest versions of Flutter. It was the default in older versions for the reasons given in comments, but if you create an empty project you will see that it no longer appears in the manifest. If it reassures you, I'll restore it, but I've just done some tests and it works perfectly.

2025-02-14 12:02 UTC, vicajilau commented on example/android/app/src/main/kotlin/com/mr/flutter/plugin/filepicker/file_picker_example/MainActivity.kt
> +package com.mr.flutter.plugin.filepicker.file_picker_example
I have recreated the android project and the folder structure has changed. The content is the same. Only the directory has changed.

2025-02-14 13:59 UTC, merged

2025-02-15 05:10 UTC, shurane commented
I guess it's too late for this PR but @vicajilau , could the `build.gradle` and `settings.gradle` be converted to the kotlin versions? i.e. `build.gradle.kts` and `settings.gradle.kts`?

2025-02-15 15:21 UTC, vicajilau commented
Yes, count on it 🚀