Fix: Handle Null Byte Array in `saveFile` Method
miguelpruivo/flutter_file_picker pull request #1662
Opened 2024-12-30 15:19 UTC by vicajilau

## Context
This PR addresses an issue in the `FilePicker.platform.saveFile` method where passing a null `Uint8List` causes failures. This issue is primarily observed on Android (API 35), but the solution is implemented for both Android and iOS to ensure consistency.

## Root Cause
The null value for `Uint8List` was not handled correctly, leading to exceptions during file operations. Specifically:
- On Android, null values caused crashes when attempting to write to the file system.

## Solution
The fix ensures that:
1. If a `Uint8List` is null, it is replaced with an empty `Uint8List(0)` before being processed.
2. The change has been tested on both Android and iOS platforms and confirmed to function without issues.

## Changes
- Updated the `saveFile` method to replace null `Uint8List` with `Uint8List(0)`.
- Ensured platform-specific implementations in both Android and iOS handle this case consistently.

## Testing
- Verified on Android API 35 to resolve the crash.
- Tested on iOS to confirm that the change does not introduce new issues.

## References
- Issue #1660 in the official repository.
- Discussion and testing logs indicate the problem is limited to null byte arrays.

## Notes
This fix aligns with the goal of ensuring robustness in file operations across platforms, avoiding unexpected crashes due to null parameter values.

## Checklist
- [x] Code changes reviewed.
- [x] Tested on Android API 35.
- [x] Tested on iOS for compatibility.

2025-02-09 07:35 UTC, vicajilau commented
Could you have a look about this @navaronbracke? :smiley:

2025-02-09 09:16 UTC, navaronbracke commented
@vicajilau I don't see any new diff on Github?

My comment above about the fix was not yet addressed also.

2025-02-10 06:54 UTC, vicajilau commented
This is the difference, if you don't send a `bytes` param in Android crash. https://github.com/miguelpruivo/flutter_file_picker/issues/1660

<img width="1160" alt="image" src="https://github.com/user-attachments/assets/af50db98-7fd9-4c60-8ac0-967d6fa30398" />

2025-02-10 06:59 UTC, navaronbracke requested changes

2025-02-10 07:00 UTC, navaronbracke commented
@vicajilau My bad, I didn't submit my last review comments. Can you take a look?

2025-02-10 23:53 UTC, PGScully commented on lib/src/file_picker_io.dart
> +        "bytes": bytes ?? Uint8List(0),
Is it user error?  If the intent is to "...pick a path for the file, that still needs to be created/written to)", then why pass bytes at all?  Just remove the parameter.

But if you are keeping bytes (and want to keep the null behaviour on MacOS), then IMO the fix could be done at line 307 of FilePickerDelegate.java:

    this.bytes = bytes ?? [];

2025-02-11 06:29 UTC, vicajilau commented on lib/src/file_picker_io.dart
> +        "bytes": bytes ?? Uint8List(0),
IMO we should move in the direction of developing Universal Applications. Let me explain. I think that packages and plugins should strive to be designed as similar as possible so that from the applications can be designed keeping a single flow for all platforms. At least as much as possible. This means that the `save` call should behave the same way on all platforms and it is the `MethodChannel` that should do the magic.

2025-02-11 07:02 UTC, vicajilau commented on lib/src/file_picker_io.dart
> +        "bytes": bytes ?? Uint8List(0),
Done!! 👍

2025-02-11 09:11 UTC, navaronbracke commented on lib/src/file_picker_io.dart
> +        "bytes": bytes ?? Uint8List(0),
@PGScully the reason why `bytes` is present as a parameter (and is nullable) is due to the `file_picker` plugin having started with a "one API fits all" approach, which isn't very ideal in the long term.

Cleaning up the API, to make it more ergonomic, is what https://github.com/miguelpruivo/flutter_file_picker/issues/1469 is going to address in the long term.

2025-02-11 09:22 UTC, navaronbracke requested changes

2025-02-11 09:22 UTC, navaronbracke commented on lib/src/file_picker_io.dart
> +        "bytes": bytes ?? Uint8List(0),
@vicajilau This is still not as expected.

Can we turn this into the following instead?

```
  @override
  Future<String?> saveFile(
      {String? dialogTitle,
      String? fileName,
      String? initialDirectory,
      FileType type = FileType.any,
      List<String>? allowedExtensions,
      Uint8List? bytes,
      bool lockParentWindow = false}) {
        if (Platform.isIOS || Platform.isAndroid) {
          if (bytes == null) {
            throw ArgumentError('Bytes are required on Android & iOS when saving a file.');
          }
        
          return _channel.invokeMethod("save", {
            "fileName": fileName,
            "fileType": type.name,
            "initialDirectory": initialDirectory,
            "allowedExtensions": allowedExtensions,
            "bytes": bytes,
          });
        }
      
   // ....    
 }
```

2025-02-11 12:33 UTC, vicajilau commented on lib/src/file_picker_io.dart
> +        "bytes": bytes ?? Uint8List(0),
Done!

2025-02-11 12:38 UTC, navaronbracke approved these changes

2025-02-11 12:38 UTC, merged