Updated dependencies
miguelpruivo/flutter_file_picker pull request #1664
Opened 2024-12-31 10:32 UTC by vicajilau

# Flutter Plugin Dependency Update

## Description

This Pull Request updates the following dependencies in the Flutter plugin to ensure compatibility with the latest versions. The update includes performance and stability improvements.

### Updated Dependencies:
- `flutter_plugin_android_lifecycle`: Updated to version ^2.0.24.
- `ffi`: Updated to version ^2.1.3.
- `path`: Updated to version ^1.9.0.
- `win32`: Updated to version ^5.9.0.
- `cross_file`: Updated to version ^0.3.4+2.
- `web`: Updated to version ^1.1.0.

## Reason for Update

- **Compatibility with new Flutter versions**: Ensuring the project is up to date with the latest dependency versions.
- **Performance and stability improvements**: Updates include various fixes that improve the stability and performance of the plugin.
- **Platform support optimization**: The updates enhance support for Android, Windows, web, and other platforms.

## Tests Performed

The update has been tested across the following platforms to ensure everything works as expected:

- [x] **Android**: No compilation or runtime issues. All functionalities work as expected.
- [x] **iOS**: The plugin was tested on a real device and operates without errors.
- [x] **Web**: Key features were tested in a modern browser (Chrome) and no issues were found.
- [x] **Windows**: Functionality was tested on Windows, and everything works as expected.

2025-02-07 19:01 UTC, navaronbracke requested changes

2025-02-08 13:15 UTC, vicajilau commented on pubspec.yaml
> +  flutter_plugin_android_lifecycle: ^2.0.24
Done 🚀

2025-02-08 13:43 UTC, navaronbracke commented on pubspec.yaml
> +  flutter_plugin_android_lifecycle: ^2.0.22
@vicajilau Do we update the changelog & version? Or do we just roll this in with the next bugfix/patch etc. ?

2025-02-08 17:51 UTC, vicajilau commented on pubspec.yaml
> +  flutter_plugin_android_lifecycle: ^2.0.22
I have already added it. I have taken the trouble to upload the versions of the CI/CD dependencies as well. If you don't like it, I'll revert it 😉

2025-02-08 20:13 UTC, navaronbracke requested changes

2025-02-08 20:13 UTC, navaronbracke commented on CHANGELOG.md
> +### General
Version 8.3.2 was already published. So this changelog entry will either need to be removed, or moved to 8.3.3 (with a version bump in the pubspec)

2025-02-09 07:29 UTC, vicajilau commented on CHANGELOG.md
> +### General
Changed!! 👍

2025-02-09 09:18 UTC, navaronbracke approved these changes

2025-02-09 09:18 UTC, merged