Add Blob Creation as Path in flutter_file_picker
miguelpruivo/flutter_file_picker pull request #1665
Opened 2024-12-31 11:45 UTC by vicajilau

# Pull Request: Add Blob Creation as Path in flutter_file_picker

## Description

This PR introduces the capability to create a blob from the picked file and set it as the path in the `flutter_file_picker` plugin. This change allows for better handling of file data directly as URLs, enhancing the flexibility of file management in web applications.

## Changes Made

- **Blob Creation**: Implemented the creation of a blob from the selected file and set it as the path in the `PlatformFile` object.
  
∑ Code Snippet

```dart
void addPickedFile(
  File file,
  Uint8List? bytes,
  String? path,
  Stream<List<int>>? readStream,
) {
  final blob = Blob([bytes ?? Uint8List(0)]);
  final blobUrl = Url.createObjectUrl(blob); // Create a blob URL

  pickedFiles.add(PlatformFile(
    name: file.name,
    path: blobUrl, // Set the blob URL as the path
    size: bytes != null ? bytes.length : file.size,
    bytes: bytes,
    readStream: readStream,
  ));

  if (pickedFiles.length >= files.length) {
    if (onFileLoading != null) {
      onFileLoading(FilePickerStatus.done);
    }
    filesCompleter.complete(pickedFiles);
  }
}
```

## Benefits
Enhanced File Handling: Allows for seamless integration of file data as URLs, making it easier to work with files in web applications.
Checklist
- [x] I have tested the changes locally.
- [x] I have updated the documentation (if applicable).
- [x] I have added any new dependencies (if applicable).
## Related Issues
- #751 
- It currently requires different flows in universal applications. This minimises the gap between platforms.

### Additional Notes
Please review the changes and let me know if further modifications are needed. Thank you! 🤗

2025-01-17 11:14 UTC, vicajilau commented
Well done @daniJimen and many thanks!!

2025-02-14 14:07 UTC, navaronbracke requested changes

2025-02-14 14:07 UTC, navaronbracke commented on lib/_internal/file_picker_web.dart
> +import 'dart:html' as html;
`dart:html` is not WASM compatible & is deprecated in Dart 3.7

2025-02-14 14:07 UTC, navaronbracke commented on lib/src/platform_file.dart
> +  final String? path;
The DartDoc comment for this getter will need to be updated.

2025-02-14 18:32 UTC, vicajilau commented on lib/_internal/file_picker_web.dart
> +import 'dart:html' as html;
Fixed!!

2025-02-14 18:43 UTC, vicajilau commented on lib/src/platform_file.dart
> +  final String? path;
Right!! But I don't have write permissions there

2025-02-14 18:57 UTC, navaronbracke commented on lib/src/platform_file.dart
> +  final String? path;
What do you mean? You can just edit the doc comment on line 35?

2025-02-14 18:58 UTC, navaronbracke commented on lib/src/platform_file.dart
> +  final String? path;
Do you mean the Wiki? I can edit the wiki right before merging.

2025-02-14 19:23 UTC, vicajilau commented on lib/src/platform_file.dart
> +  final String? path;
Yes 🤗

2025-02-15 12:20 UTC, vicajilau commented on lib/src/platform_file.dart
> +  final String? path;
Got it! Changed DartDoc on 35 line :rocket:

2025-02-15 12:24 UTC, navaronbracke requested changes

2025-02-15 12:24 UTC, navaronbracke commented on lib/_internal/file_picker_web.dart
> +        final blobParts = bytes ?? Uint8List(0);
Can we avoid allocating a Blob if the bytes is null / empty?

I also worry about leaking the underlying Blob, as the url from `URL.createObjectURL()` is not getting freed with 
https://pub.dev/documentation/web/latest/web/URL/revokeObjectURL.html

2025-02-15 12:24 UTC, navaronbracke commented on lib/src/platform_file.dart
> +  /// On web, this will return a blob URL instead of a file path.
```suggestion
  /// On web the path points to a Blob URL, if present.
```

2025-02-15 15:19 UTC, vicajilau commented on lib/_internal/file_picker_web.dart
> +        final blobParts = bytes ?? Uint8List(0);
Removed! I am aware that it is not released, but I have not had any problems associated with this. Do you suggest another approach? I think it is worth unifying the flows 🚀

2025-02-15 19:34 UTC, navaronbracke requested changes

2025-02-15 19:34 UTC, navaronbracke commented on lib/_internal/file_picker_web.dart
> +        if (bytes != null) {
We should probably also check that the length of the bytes isn't zero? That is just a sanity check, but you never know what users will do.

2025-02-15 19:34 UTC, navaronbracke commented on lib/src/platform_file.dart
> +  /// On web the path points to a Blob URL, if present.
Should we perhaps tell users to call `URL.revokeObjectURL` on the path when they are done with the file (on web)?

```suggestion
/// On web the path points to a Blob URL, if present, which can be cleaned up using [URL.revokeObjectURL].
```

2025-02-15 19:34 UTC, navaronbracke commented on CHANGELOG.md
> +- **BREAKING CHANGE:** `pickFiles()` now loads files as blobs. See the note in the updated [wiki](https://github.com/miguelpruivo/flutter_file_picker/wiki/api#-pickfiles)
Breaking changes should bump the major version, though.

2025-02-15 19:37 UTC, vicajilau commented on lib/_internal/file_picker_web.dart
> +        if (bytes != null) {
Done!!

2025-02-15 19:38 UTC, vicajilau commented on CHANGELOG.md
> +- **BREAKING CHANGE:** `pickFiles()` now loads files as blobs. See the note in the updated [wiki](https://github.com/miguelpruivo/flutter_file_picker/wiki/api#-pickfiles)
Makes sense!! Done 🚀

2025-02-15 20:19 UTC, navaronbracke approved these changes

2025-02-15 20:19 UTC, merged

2025-02-15 20:19 UTC, navaronbracke commented
@vicajilau I updated the note on the Wiki as well