Add the capability of retrieving 'lost' files after activity being de…
miguelpruivo/flutter_file_picker pull request #488
Opened 2020-11-09 17:07 UTC by biessek

Based on [image_picker](https://pub.dev/packages/image_picker) plugin, I've added the same logic to retrieve 'lost' files selection after activity destruction on Android, This can occur by different reasons and I've seen it happening a lot on huawei and xiaomi devices.

After calling `pickFiles` if the app `Activity` is destroyed, the user can retrieve the "lost selection" by calling `retrieveLostData'. I'm using this functionality in some apps and maybe it can be useful to others as well.

2020-11-09 17:14 UTC, miguelpruivo commented
@biessek hi, thank you for your PR. Although this looks like a nice idea at first, I'd rather to not have another object on the Dart side and let this logic being purely handled on the Android side (save/restore instance). 

Do you think that it can be done?

Thank you!

2020-11-09 17:19 UTC, biessek commented
I understand you @miguelpruivo , I also think that it is not the ideal way, but from my experience I don't think there is any other way for now. Since when the activity is destroyed by Android OS, the "link" between native / flutter made by `MethodCall` is lost, so this new link is established with` retrieveLostData`

2021-08-23 09:48 UTC, miguelpruivo requested changes
Can you please rebase it to latest version? Thank you!

2021-08-29 19:50 UTC, biessek commented
Done @miguelpruivo

2022-05-03 22:56 UTC, closed without merging

2024-10-10 20:09 UTC, chowdhuryrahulc approved these changes