fix PlatformFile path is always null on web
miguelpruivo/flutter_file_picker pull request #754
Opened 2021-06-22 21:11 UTC by maxzod

i have searched on the web and on this repository issues and i cant figure out why 
i didn't read the docs very will i thought that file picker will only need the permissions  😐
but i was wrong 😅😅

i have made some changes to make it clear for others to figure it out it easily 
now no one will buzzer you with this issue any more 😅😅

2021-08-23 09:46 UTC, miguelpruivo requested changes
Could you please run `flutter format .`?

2021-08-23 10:11 UTC, maxzod commented
i made it put it didn't change anything
![image](https://user-images.githubusercontent.com/47630729/130430257-953f231e-88a2-4ab5-b9c0-1be33eb37f51.png)

2021-08-30 19:51 UTC, miguelpruivo approved these changes

2021-08-30 19:51 UTC, merged

2021-08-30 19:51 UTC, miguelpruivo commented
Thank you.